-- sim/param_docs.lua — Kurzbeschreibung JEDES Parameters aus sim/model.lua
-- (GDD 17.6, Runde 9 #119). Das F10-Panel zeigt sie beim Verweilen auf einer
-- Zeile. Reines Lua, love-frei.
--
-- Format: key = { "Was er regelt.", "hoeher = Wirkungsrichtung" }
-- Regeln (per tests/unit_panel.lua erzwungen):
--   * KEINE Zahlen im Text — der Tooltip zeigt den Live-Wert daneben;
--     harte Zahlen veralten beim ersten Tuning.
--   * ASCII-only (Spielcode-Konvention), erster Satz endet auf einem Punkt,
--     zweiter beginnt mit "hoeher = ".
--   * Jeder Parameter braucht einen Eintrag, sonst wird die Suite rot.

return {
  -- Hogger: Statemachine (9.1) ---------------------------------------------
  hogger_aggro_radius = { "Umkreis, in dem Hogger von selbst in den Kampf geht.",
    "hoeher = er reagiert frueher" },
  hogger_no_contact_reset = { "Zeit ohne Ziel und ohne Treffer, bis Hogger heimtrabt und der Try endet.",
    "hoeher = Kiten und Wipes werden laenger geduldet" },

  -- Hogger: Werte und Faehigkeiten (9.2) -----------------------------------
  hogger_autohit_dmg = { "Schaden eines Hogger-Autohits.",
    "hoeher = Spieler sterben schneller" },
  hogger_autohit_interval = { "Zeit zwischen zwei Hogger-Autohits.",
    "hoeher = er schlaegt seltener zu" },
  hogger_speed = { "Lauftempo von Hogger.",
    "hoeher = Weglaufen hilft weniger" },
  hogger_zone_radius = { "Hoggers Revier: Charge-Reichweite ab ihm und Groesse der Huegelzone.",
    "hoeher = die Charge greift weiter nach hinten" },
  hogger_cleave_divisor = { "Teiler, der aus der Raidgroesse die Zahl der Cleave-Ziele macht.",
    "hoeher = weniger Ziele je Schlag" },
  hogger_charge_cd = { "Abklingzeit der Rushing Charge.",
    "hoeher = weniger Druck auf die Backline" },
  hogger_charge_dmg = { "Schaden der Rushing Charge.",
    "hoeher = die Charge toetet oefter" },
  hogger_charge_knockback = { "Rueckstoss, den die Charge dem Ziel verpasst.",
    "hoeher = das Ziel fliegt weiter" },
  hogger_charge_windup = { "Anlaufzeit mit blinkender Ziellinie vor der Charge.",
    "hoeher = mehr Zeit zum Ausweichen" },
  hogger_slice_dmg = { "Sofortschaden des Vicious Slice.",
    "hoeher = der Anriss trifft haerter" },
  hogger_slice_cd = { "Abklingzeit des Vicious Slice.",
    "hoeher = seltener Blutungen" },
  hogger_slice_duration = { "Wirkdauer der Blutung.",
    "hoeher = mehr Ticks je Anriss" },
  hogger_slice_bleed_dmg = { "Schaden je Blutungstick nach dem Vicious Slice.",
    "hoeher = Blutungen toeten oefter" },
  hogger_slice_bleed_interval = { "Zeit zwischen zwei Blutungsticks.",
    "hoeher = die Blutung tickt langsamer" },
  add_hp = { "Lebenspunkte eines Gnoll-Welpen.",
    "hoeher = Welpen binden laenger Aufmerksamkeit" },
  add_dmg = { "Schaden eines Gnoll-Welpen je Treffer.",
    "hoeher = Welpen toeten Stoffklassen schneller" },
  add_attack_interval = { "Zeit zwischen zwei Angriffen eines Gnoll-Welpen.",
    "hoeher = Welpen schlagen seltener" },
  eat_cd = { "Abklingzeit zwischen zwei Fressversuchen.",
    "hoeher = Hogger frisst seltener" },
  eat_corpse_radius = { "Umkreis, in dem Hogger eine Leiche zum Fressen sucht.",
    "hoeher = er findet oefter Futter" },
  eat_hp_threshold = { "HP-Anteil, unter dem Hogger ueberhaupt zu fressen beginnt.",
    "hoeher = er frisst schon frueh im Try" },
  eat_drag_duration = { "Dauer, in der Hogger die Leiche zu sich zieht.",
    "hoeher = mehr Vorwarnung" },
  eat_channel_duration = { "Dauer des Fress-Kanals, in dem unterbrochen werden muss.",
    "hoeher = mehr Zeit zum Unterbrechen" },
  eat_heal_rate = { "Anteil der Maximal-HP, den Hogger je Sekunde frisst.",
    "hoeher = Fressen heilt ihn schneller" },
  eat_dmg_threshold_pct = { "Schadensanteil im Kanal, der das Fressen allein schon unterbricht.",
    "hoeher = Unterbrechen per Schaden wird schwerer" },

  -- Hogger: Skalierung (9.3) ------------------------------------------------
  hogger_hp_quad = { "Quadratischer Anteil der HP-Formel.",
    "hoeher = grosse Raids bekommen ueberproportional HP" },
  hogger_hp_slope = { "Linearer Anteil der HP-Formel je Spieler.",
    "hoeher = Hogger haelt bei jeder Groesse laenger" },
  hogger_hp_offset = { "Sockelabzug in Hoggers HP-Formel.",
    "hoeher = kleine Raids haben es leichter" },
  add_divisor = { "Teiler, der aus der Raidgroesse die Zahl der Gnoll-Welpen macht.",
    "hoeher = weniger Welpen je Raidgroesse" },
  eat_interrupt_divisor = { "Teiler, der aus der Raidgroesse die noetigen Unterbrecher macht.",
    "hoeher = weniger Unterbrecher noetig" },
  eat_interrupt_offset = { "Aufschlag auf die Zahl der noetigen Unterbrecher.",
    "hoeher = Unterbrechen braucht mehr Leute" },
  respawn_base = { "Fester Sockel des Respawn-Timers in Sekunden.",
    "hoeher = laengere Todesstrafe fuer alle" },
  respawn_factor = { "Anteil, mit dem die Raidgroesse den Respawn-Timer streckt.",
    "hoeher = grosse Raids warten laenger" },
  respawn_min = { "Untergrenze des Respawn-Timers.",
    "hoeher = auch kleine Raids warten laenger" },
  respawn_max = { "Obergrenze des Respawn-Timers.",
    "hoeher = die Deckelung greift spaeter" },

  -- Bedrohung (9.4) ---------------------------------------------------------
  threat_per_damage = { "Bedrohung je Punkt ausgeteiltem Schaden.",
    "hoeher = Schadensspitzen ziehen Aggro" },
  threat_per_heal = { "Bedrohung je Punkt Heilung.",
    "hoeher = Heiler ziehen frueher Aggro" },

  -- Spieler: Basiswerte (8.1) ----------------------------------------------
  move_speed_alive = { "Lauftempo lebender Spieler.",
    "hoeher = kuerzerer Anmarsch" },
  move_speed_ghost = { "Lauftempo als Geist.",
    "hoeher = kuerzere Todesstrafe" },
  autohit_melee_dmg = { "Schaden eines Nahkampf-Autohits.",
    "hoeher = mehr Grundschaden ohne Ressourcen" },
  autohit_interval = { "Zeit zwischen zwei Nahkampf-Autohits der Spieler.",
    "hoeher = weniger Grundschaden" },
  autoshot_dmg = { "Schaden des Jaeger-Autoschusses.",
    "hoeher = Jaeger tragen mehr Dauerlast" },
  autoshot_range = { "Reichweite des Jaeger-Autoschusses.",
    "hoeher = Jaeger stehen sicherer" },
  cast_range = { "Reichweite aller Angriffszauber der Caster.",
    "hoeher = Caster stehen weiter hinten" },
  melee_range = { "Reichweite, ab der ein Nahkampfangriff trifft.",
    "hoeher = Nahkaempfer treffen aus mehr Abstand" },
  heal_range = { "Reichweite der Heilzauber auf andere Spieler.",
    "hoeher = Heiler stehen sicherer" },
  gcd = { "Globale Abklingzeit zwischen zwei Faehigkeiten.",
    "hoeher = traegeres Spielgefuehl" },
  facing_arc_deg = { "Blickwinkel, in dem Angriffe durchgehen; Vollkreis schaltet die Regel ab.",
    "hoeher = Wegdrehen bestraft weniger" },
  hp_plate = { "Lebenspunkte der Plattenklassen.",
    "hoeher = Krieger und Paladine halten laenger" },
  hp_leather = { "Lebenspunkte der Leder- und Schwerklassen.",
    "hoeher = Jaeger, Schurken und Druiden halten laenger" },
  hp_cloth = { "Lebenspunkte der Stoffklassen.",
    "hoeher = Caster halten laenger" },
  mana_max = { "Manavorrat aller Zauberklassen.",
    "hoeher = mehr Zauber je Leben" },
  five_sec_rule_wait = { "Cast-Pause, nach der Mana wieder zu regenerieren beginnt.",
    "hoeher = laengere Durststrecke fuer Caster" },
  mana_regen_rate = { "Mana je Sekunde ausserhalb der Cast-Sperre.",
    "hoeher = Caster sind seltener leer" },
  rage_max = { "Wutvorrat des Kriegers.",
    "hoeher = mehr Wut zum Ausgeben" },
  rage_per_hit_taken = { "Wut je erlittenem Treffer.",
    "hoeher = Pruegel zahlen sich mehr aus" },
  rage_per_hit_dealt = { "Wut je ausgeteiltem Autohit.",
    "hoeher = Krieger kommen schneller ins Rollen" },
  energy_max = { "Energievorrat des Schurken.",
    "hoeher = laengere Angriffsserien" },
  energy_regen_rate = { "Energie, die der Schurke je Sekunde zurueckgewinnt.",
    "hoeher = seltener Leerlauf" },

  -- Klassen: Faehigkeiten (8.2) --------------------------------------------
  warrior_heroic_dmg = { "Schaden des Heroischen Stosses.",
    "hoeher = Krieger tragen mehr bei" },
  warrior_heroic_rage = { "Wutkosten des Heroischen Stosses.",
    "hoeher = seltener zuschlagen" },
  warrior_shout_bonus = { "Schadensanteil, den der Schlachtruf Verbuendeten schenkt.",
    "hoeher = Krieger werden zur Stuetze" },
  warrior_shout_duration = { "Wirkdauer des Schlachtrufs.",
    "hoeher = seltener nachbuffen" },
  warrior_shout_radius = { "Umkreis, in dem der Schlachtruf Verbuendete erfasst.",
    "hoeher = mehr Spieler profitieren" },
  warrior_shout_rage = { "Wutkosten des Schlachtrufs.",
    "hoeher = der Buff kostet mehr Schaden" },
  paladin_holylight_heal = { "Heilung des Heiligen Lichts.",
    "hoeher = Paladine retten mehr" },
  paladin_holylight_cast = { "Zauberzeit des Heiligen Lichts.",
    "hoeher = die Notheilung kommt spaeter" },
  paladin_holylight_mana = { "Manakosten des Heiligen Lichts.",
    "hoeher = weniger Notheilungen je Leben" },
  paladin_seal_hits = { "Zahl der Autohits, die das Siegel verstaerkt.",
    "hoeher = das Siegel wirkt laenger" },
  paladin_seal_bonus_dmg = { "Zusatzschaden je Autohit unter dem Siegel.",
    "hoeher = Paladine schlagen haerter zu" },
  paladin_seal_mana = { "Manakosten des Siegels der Rechtschaffenheit.",
    "hoeher = seltener nachbuffen" },
  hunter_raptor_dmg = { "Schaden des Raptorstosses.",
    "hoeher = mehr Burst aus der Nahdistanz" },
  hunter_raptor_cd = { "Abklingzeit des Raptorstosses.",
    "hoeher = seltener Nahkampf-Burst" },
  rogue_sinister_dmg = { "Schaden des Finsteren Stosses.",
    "hoeher = Schurken tragen mehr bei" },
  rogue_sinister_energy = { "Energiekosten des Finsteren Stosses.",
    "hoeher = weniger Combopunkte je Leben" },
  rogue_evis_dmg_per_cp = { "Schaden des Ausweidens je Combopunkt.",
    "hoeher = der Finisher trifft haerter" },
  rogue_evis_energy = { "Energiekosten des Ausweidens.",
    "hoeher = seltener finishen" },
  rogue_stealth_speed = { "Tempoanteil in der Verstohlenheit.",
    "hoeher = Schurken schleichen schneller" },
  priest_smite_dmg = { "Schaden der Goettlichen Pein.",
    "hoeher = Priester tragen mehr bei" },
  priest_smite_cast = { "Zauberzeit der Goettlichen Pein.",
    "hoeher = weniger Schaden vom Priester" },
  priest_smite_mana = { "Manakosten der Goettlichen Pein.",
    "hoeher = Schaden kostet Heilung" },
  priest_heal_amount = { "Heilung des Geringen Heilens.",
    "hoeher = Priester halten den Raid laenger" },
  priest_heal_cast = { "Zauberzeit des Geringen Heilens.",
    "hoeher = Heilung kommt oefter zu spaet" },
  priest_heal_mana = { "Manakosten des Geringen Heilens.",
    "hoeher = Priester gehen frueher leer" },
  mage_fireball_dmg = { "Schaden des Feuerballs.",
    "hoeher = Magier werden zur Glaskanone" },
  mage_fireball_cast = { "Zauberzeit des Feuerballs.",
    "hoeher = der groesste Einzelhit kommt spaeter" },
  mage_fireball_mana = { "Manakosten des Feuerballs.",
    "hoeher = Magier gehen frueher leer" },
  mage_frostarmor_slow = { "Anteil, um den Hogger nach einem Treffer verlangsamt wird.",
    "hoeher = Magier bremsen den Boss staerker" },
  mage_frostarmor_slow_duration = { "Dauer der Verlangsamung durch die Frostruestung.",
    "hoeher = der Bremseffekt haelt laenger" },
  warlock_bolt_dmg = { "Schaden des Schattenblitzes.",
    "hoeher = Hexer tragen mehr bei" },
  warlock_bolt_cast = { "Zauberzeit des Schattenblitzes.",
    "hoeher = weniger Zauber je Minute" },
  warlock_bolt_mana = { "Manakosten des Schattenblitzes.",
    "hoeher = Hexer gehen frueher leer" },
  warlock_imp_cast = { "Zauberzeit der Wichtel-Beschwoerung.",
    "hoeher = das Pet steht spaeter" },
  warlock_imp_mana = { "Manakosten der Wichtel-Beschwoerung.",
    "hoeher = Beschwoeren kostet mehr Zauber" },
  imp_hp = { "Lebenspunkte des Wichtels.",
    "hoeher = das Pet haelt Aggro laenger" },
  imp_dmg = { "Schaden eines Feuerblitzes des Wichtels.",
    "hoeher = das Pet traegt mehr bei" },
  imp_interval = { "Zeit zwischen zwei Feuerblitzen des Wichtels.",
    "hoeher = das Pet schiesst seltener" },
  druid_wrath_dmg = { "Schaden des Druiden-Zorns.",
    "hoeher = Druiden tragen mehr Schaden bei" },
  druid_wrath_cast = { "Zauberzeit des Druiden-Zorns.",
    "hoeher = weniger Zauber je Minute" },
  druid_wrath_mana = { "Manakosten des Druiden-Zorns.",
    "hoeher = die Hybridrolle wird enger" },
  druid_touch_heal = { "Heilung der Heilenden Beruehrung.",
    "hoeher = Druiden retten mehr" },
  druid_touch_cast = { "Zauberzeit der Heilenden Beruehrung des Druiden.",
    "hoeher = die grosse Heilung kommt spaeter" },
  druid_touch_mana = { "Manakosten der Heilenden Beruehrung.",
    "hoeher = weniger Heilungen je Leben" },

  -- Mobs und Loot (7.2 / 7.3) ----------------------------------------------
  boar_hp = { "Lebenspunkte eines Wildschweins.",
    "hoeher = zaehere Wildschweine" },
  boar_dmg = { "Schaden eines Wildschweins je Treffer.",
    "hoeher = Wildschweine sind gefaehrlicher" },
  boar_flee_hp_pct = { "HP-Anteil, ab dem ein Wildschwein die Flucht ergreift.",
    "hoeher = es flieht frueher" },
  wolf_hp = { "Lebenspunkte eines Wolfs.",
    "hoeher = zaehere Woelfe" },
  wolf_dmg = { "Schaden eines Wolfs je Treffer.",
    "hoeher = Woelfe sind gefaehrlicher" },
  wolf_aggro_radius = { "Umkreis, in dem ein Wolf von selbst angreift.",
    "hoeher = Woelfe ziehen frueher los" },
  kobold_hp = { "Lebenspunkte eines Kobolds.",
    "hoeher = zaehere Kobolde" },
  kobold_dmg = { "Schaden eines Kobolds je Treffer.",
    "hoeher = Kobolde sind gefaehrlicher" },
  murloc_hp = { "Lebenspunkte eines Murlocs.",
    "hoeher = zaehere Murlocs" },
  murloc_dmg = { "Schaden eines Murlocs je Treffer.",
    "hoeher = Murlocs sind gefaehrlicher" },
  mob_attack_interval = { "Zeit zwischen zwei Mob-Angriffen.",
    "hoeher = Mobs schlagen seltener" },
  mob_respawn = { "Zeit, bis ein erschlagener Mob an seinem Punkt wiederkehrt.",
    "hoeher = die Wiese bleibt laenger leer" },
  mob_slot_base = { "Grundzahl aktiver Mob-Plaetze unabhaengig von der Raidgroesse.",
    "hoeher = mehr Ablenkung am Wegesrand" },
  mob_slot_divisor = { "Teiler, mit dem die Raidgroesse zusaetzliche Mob-Plaetze oeffnet.",
    "hoeher = weniger Mobs bei grossen Raids" },
  mob_patrol_radius = { "Umkreis, in dem Mobs im Leerlauf herumspazieren.",
    "hoeher = weitere Wege, lebendigere Wiese" },
  mob_patrol_speed = { "Gehtempo der Mobs im Leerlauf.",
    "hoeher = sie wirken hektischer" },
  xp_per_mob = { "Erfahrung je erschlagenem Mob.",
    "hoeher = schneller zum DING" },
  xp_level2 = { "Erfahrung bis zur naechsten Stufe, das Ziel des Erfahrungsbogens.",
    "hoeher = das DING dauert laenger" },

  -- Loop und Todesstrafe (5 / 6 / 7.1 / 11) --------------------------------
  try_time_limit = { "Laenge eines Trys in Sekunden, bevor die Uhr ihn beendet.",
    "hoeher = mehr Zeit je Anlauf" },
  release_grace = { "Nachfrist, nach der ein Toter von selbst zum Geist wird.",
    "hoeher = laenger liegen bleiben" },
  revive_channel = { "Dauer des Wiederbelebungs-Channels auf dem Klassenicon.",
    "hoeher = Wiederbeleben dauert laenger" },
  graveyard_to_field_dist = { "Geisterlauf vom Friedhof bis zum Wiederbelebungsfeld.",
    "hoeher = laengerer Geisterlauf" },
  field_to_hill_dist = { "Laufweg vom Wiederbelebungsfeld bis zu Hoggers Huegel.",
    "hoeher = laengerer Anmarsch nach dem Tod" },

  -- Krits (13.2) ------------------------------------------------------------
  crit_chance_player = { "Kritchance der Spieler.",
    "hoeher = mehr Zufall im Raidschaden" },
  crit_mult_player = { "Schadensfaktor eines Spieler-Krits.",
    "hoeher = Krits reissen mehr Boss-HP" },
  crit_chance_hogger = { "Kritchance von Hogger und seinen Adds.",
    "hoeher = mehr Zufall in den Spielertoden" },
  crit_mult_hogger = { "Schadensfaktor eines Hogger-Krits.",
    "hoeher = Krits toeten haerter" },

  -- Leeroy und Echo (10 / 10.3) --------------------------------------------
  leeroy_threat_factor = { "Anteil, mit dem Leeroys Schaden auf die Bedrohung zaehlt.",
    "hoeher = Hogger bleibt oefter an Leeroy" },
  leeroy_announcer_throttle = { "Mindestabstand zwischen zwei Leeroy-Ansagen.",
    "hoeher = Leeroy redet seltener" },
  leeroy_kragen_trys = { "Ab welchem Try Leeroy den Fress-Hinweis als Sicherheitsnetz gibt.",
    "hoeher = der Tipp kommt spaeter" },
  leeroy_stuck_timeout = { "Zeit ohne Fortschritt, ab der Leeroys Failsafe ihn loest.",
    "hoeher = er haengt laenger fest" },
  leeroy_first_march_wait = { "Wartezeit des Raid-Leeroy vor seinem ersten Anmarsch.",
    "hoeher = der erste Try startet spaeter" },

  -- UI und Kamera (4.1 / 4.2) ----------------------------------------------
  floating_text_max = { "Obergrenze gleichzeitiger Schadenszahlen auf dem Schirm.",
    "hoeher = mehr Zahlen, unruhigeres Bild" },
  floating_text_duration = { "Standzeit einer Schadenszahl an den Icons.",
    "hoeher = Zahlen bleiben laenger stehen" },
  zoom_radius_1 = { "Sichtradius der Minimap auf der nahen Zoomstufe.",
    "hoeher = mehr Karte, kleinere Icons" },
  zoom_radius_2 = { "Sichtradius der Minimap auf der mittleren Zoomstufe.",
    "hoeher = mehr Karte, kleinere Icons" },
  zoom_radius_3 = { "Sichtradius der Minimap auf der weiten Zoomstufe.",
    "hoeher = mehr Karte, kleinere Icons" },

  -- Sim-Modell, nur Headless (17.2) ----------------------------------------
  sim_skill_min = { "Untergrenze des Spielerkoennens in der Balancing-Sim.",
    "hoeher = die Sim rechnet mit weniger Ausreissern" },
  sim_skill_max = { "Obergrenze des Spielerkoennens in der Balancing-Sim.",
    "hoeher = die Sim rechnet mit staerkeren Spielern" },
  sim_group_factor_min = { "Untergrenze des Gruppenfaktors in der Balancing-Sim.",
    "hoeher = die Sim rechnet mit weniger Chaos" },
  sim_group_factor_max = { "Obergrenze des Gruppenfaktors in der Balancing-Sim.",
    "hoeher = die Sim rechnet mit besserer Koordination" },
}
